config/routes.rb
Rails.application.routes.draw do
  get "/", to: "sessions#new"
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :firstname, :lastname,presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 }
    validates :email, uniqueness: true
    has_secure_password
    validates :password, length: { minimum: 6 }
    validates :birthday, :gender, presence: true

    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :login_required
    private
    def login_required
        redirect_to new_session_path unless logged_in?
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  def new
    @post= Post.new
    @post.user_id = current_user.id
  end

  def create
    @post= Post.new(post_params)
    @post.user_id = current_user.id
    if params[:back]
      render:new
    else
      if @post.save
        redirect_to posts_path, notice: "Post was successfully updated."
      else
        render :new
      end 
    end
  end

  def edit
    unless current_user.id == @post.user_id
      redirect_to posts_path, notice: "You are not allowed to do this action"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    unless current_user.id == set_post.user_id
      redirect_to posts_path, notice: "You are not allowed to do this action"
    end
    set_post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted."
  end

  def show
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash.now[:danger] = "Credentials not recognized"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end
  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :gender, :birthday, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_posts_path
        elsif action_name == 'edit'
            post_path
        else
            posts_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsConnection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="wlink_textidth=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Friends Connection</h5>
      <% if logged_in? %>
        <%= link_to  "New post", new_post_path, class:"btn btn-outline-primary mr-3" %>
        <%= link_to  "All post", posts_path, class:"btn btn-outline-primary mr-3" %>
        <%= link_to  "Logout", session_path(current_user.id), method: :delete, data:{confirm: "Are you sure ?"}, class:"btn btn-outline-primary mr-3"  %>
      <% else %>
        <%= link_to  "Sign in", new_session_path, class:"btn btn-outline-primary mr-3" %>
        <%= link_to  "Sign up", new_user_path, class:"btn btn-outline-primary" %>
      <% end %>
    </div>
    <div class="main">
      <%= yield %>
    </div>
    <footer class="pt-4 border-top">
          <div class="col-12 col-md">
            <span>DiveIntoCode | All right reserved &copy; 2021</span>
          </div>
      </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit) do |f| %>
    <div class="form-group">
        <%= f.text_area :content, class:"form-control", placeholder:"Content" %>
    </div>
    <%= image_tag @post.image.url, class:"w-100" if @post.image && @post.image.url %>
    <div class="form-group">
        <%= f.file_field :image, class:"form-control-file" %>
    </div>
    <%= f.hidden_field :image_cache %>
    <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/posts/confirm.html.erb
<div class="container">
    <h1>Confirm</h1>

    <%= form_with(model: @post, local: true) do |f| %>
        <%= f.hidden_field :content, class:"form-control", placeholder:"Content" %>
        <%= f.hidden_field :image, class:"form-control-file" %>
        <%= f.hidden_field :image_cache %>
        <p> <%=@post.content%> 
            <%= image_tag @post.image.url, class:"w-100" if @post.image && @post.image.url %>
        </p>
        <%= f.submit  "Confirm", class:"btn btn-success" %>
        <%= f.submit"Back", name: 'back', class:"btn btn-primary" %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container my-3">
    <h1>Update Post</h1>
    
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <h1>Posts</h1>
    
    <% if notice.present? %>
        <div class="alert alert-info">
            <p id="notice"><%= notice %></p>
        </div>
    <% end %>
    
    <div class="d-flex">
        <% @posts.each do |post| %>
            <div class="card mt-3 mr-3" style="width: 18rem;">
                <%= image_tag post.image.url, class:"card-img-top" %>
                <div class="card-body">
                    <p class="card-text"><%=post.content%></p>
                    <%= link_to 'Show', post_path(post.id),class:"btn btn-primary mr-3" %> 
                    <p class="author">By <b><%= post.user.firstname+" "+post.user.lastname%></b> </p>
                </div>
            </div>
        <% end %>
    </div>
    
</div>

app/views/posts/new.html.erb
<div class="container my-3">
    <h1>New Post</h1>
    
    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container my-2">
    <div class="card" style="width: 100%;">
        <%= image_tag @post.image.url, class:"card-img-top" %>
        <div class="card-body">
            <p class="card-text"><%=@post.content%></p>
            
            <% if @post.user_id == current_user.id %>
                <%= link_to 'Edit', edit_post_path(@post),class:"btn btn-warning mr-3" %> 
                <%= link_to "Delete", post_path(@post),class:"btn btn-danger mr-3", method: "delete", data:{ confirm: "Are you sure ?" } %>
            <% end %>
            
            <p class="author">By <b><%= @post.user.firstname+" "+@post.user.lastname%></b> </p>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container my-2">
    <div class="row">
        <div class="col col-md-6 d-flex align-self-center">
            <div class="company-text">
                <h2 class="font-weight-bold text-primary">friends connection</h2>
                <p>Be connect with your friends with friends connection, do post and share picture</p>
                <% if @user.errors.any? %> 
                    <div class="text-danger"> 
                        <ul> 
                            <% @user.errors.full_messages.each do |message| %> 
                                <li><%= message %></li> 
                            <% end %> 
                        </ul> 
                    </div> 
                <% end %> 
            </div>
        </div>
        <div class="col col-md-6 form">
            <%= form_with(model: @user, local: true) do |f| %>
                <div class="form-group">
                    <%= f.text_field :firstname, class:"form-control", placeholder:"Firstname" %>
                </div>
                <div class="form-group">
                    <%= f.text_field :lastname, class:"form-control", placeholder:"Lastname" %>
                </div>
                <div class="form-group">
                    <%= f.email_field :email, class:"form-control", placeholder:"Email" %>
                </div>
                <div class="form-group">
                    <%= f.label :birthday, "Birthday" %>
                    <%= f.date_field :birthday, class:"form-control" %>
                </div>
                <div class="form-group">
                    <div><%= f.label "Gender" %></div> 
                    <div class="form-check form-check-inline">
                        <%= f.radio_button :gender, "male", checked: true%> 
                        <%= f.label "Male", class:"form-check-label" %>
                    </div>
                    <div class="form-check form-check-inline">
                        <%= f.radio_button :gender, "female" %> 
                        <%= f.label "Female", class:"form-check-label" %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
                </div>
                <div class="form-group">
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password" %>
                </div>
                <div class="text-center">
                    <%= f.submit "Submit", class:"btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>